import { defineRule } from "./define.js";
import type { Language, LintMode, LintRule } from "./types.js";

// Every current rule targets the JS/TS family (lint-shared.mjs SUPPORTED_EXTS).
const JSTS: Language[] = ["typescript", "javascript"];

// Common mode sets. Per-source and metric rules share the file-based modes;
// ratchet rules add --push (diff-aware) via dup-ratchet/runRatchetHook.
const FILE_MODES: LintMode[] = ["staged", "all", "files", "warn"];
const RATCHET_MODES: LintMode[] = ["push", "staged", "all", "files", "warn"];

/**
 * Seed input for the registry DB. Metadata is derived from each hook's behavior
 * and shared constants (FN_LIMITS, CLASS_LIMITS). The DB is the home of record;
 * this array only feeds `seed-rules`.
 */
export const RULES: LintRule[] = [
  defineRule({
    slug: "lint-comments",
    name: "Comment hygiene",
    category: "comments",
    description:
      "Flags empty, malformed, or excessive consecutive comments; discourages block comments.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: ["staged", "files"],
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-complexity",
    name: "Cyclomatic complexity",
    category: "complexity",
    description: "Flags functions whose cyclomatic complexity exceeds the limit.",
    languages: JSTS,
    config: { maxComplexity: 15 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-dead-code",
    name: "Dead code",
    category: "dead-code",
    description: "Detects unused files, exports, and enum members (knip).",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "lint-prettier",
    name: "Prettier formatting",
    category: "formatting",
    description:
      "Flags files that are not Prettier-formatted (prettier --check); the fix action runs prettier --write.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
    actions: [
      {
        kind: "script",
        scriptPath: "hooks/git/lint-prettier.mjs",
        description:
          "Reformat with prettier --write (invoke the hook with --fix).",
      },
    ],
  }),
  defineRule({
    slug: "lint-dup",
    name: "Token duplication",
    category: "duplication",
    description: "Detects token-based copy-paste clones across the repo (jscpd).",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "lint-dup-fn",
    name: "Duplicate functions",
    category: "duplication",
    description: "Detects duplicated function bodies (AST clones) in production code.",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "lint-dup-structural",
    name: "Structural duplication",
    category: "duplication",
    description: "Detects repeated structural patterns (e.g. sibling tables), ratcheted against baseline.",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "lint-emitter-casing",
    name: "Emitter event casing",
    category: "naming",
    description: "Enforces case conventions for EventEmitter event names in template literals.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-empty-catch",
    name: "Empty catch blocks",
    category: "error-handling",
    description: "Blocks empty catch blocks; requires a narrow rethrow, predicate, or logged warning.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-frozen-interfaces",
    name: "Frozen interfaces",
    category: "api-stability",
    description: "Prevents changes to signatures marked frozen (baseline in interface-frozen.yaml).",
    languages: [],
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-max-lines",
    name: "Max lines per function",
    category: "size",
    description: "Flags functions longer than the line limit.",
    languages: JSTS,
    config: { maxLines: 60 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-max-file-lines",
    name: "Max lines per file",
    category: "size",
    description: "Flags source files longer than the line limit.",
    languages: JSTS,
    config: { maxFileLines: 300 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-max-line-length",
    name: "Max line length",
    category: "size",
    description: "Flags lines wider than the column limit.",
    languages: JSTS,
    config: { maxLineLength: 100 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-max-params",
    name: "Max parameters per function",
    category: "size",
    description: "Flags functions with more than the allowed number of parameters.",
    languages: JSTS,
    config: { maxParams: 3 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-max-statements",
    name: "Max statements per function",
    category: "size",
    description: "Flags functions with more than the allowed number of statements.",
    languages: JSTS,
    config: { maxStatements: 20 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-naming",
    name: "Naming conventions",
    category: "naming",
    description: "PascalCase for types/classes; camelCase/PascalCase/UPPER_SNAKE for values (blocks snake_case).",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-solid-s",
    name: "SOLID — Single Responsibility",
    category: "solid",
    description: "Flags classes with weak cohesion or too many dependencies (LCOM4, deps).",
    languages: JSTS,
    config: { lcom4: 1, deps: 8 },
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-solid-o",
    name: "SOLID — Open/Closed",
    category: "solid",
    description: "Flags violations of the Open/Closed principle.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-solid-l",
    name: "SOLID — Liskov Substitution",
    category: "solid",
    description: "Flags violations of the Liskov Substitution principle.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-solid-i",
    name: "SOLID — Interface Segregation",
    category: "solid",
    description: "Flags violations of the Interface Segregation principle.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-solid-d",
    name: "SOLID — Dependency Inversion",
    category: "solid",
    description: "Flags violations of the Dependency Inversion principle.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-sync-calls",
    name: "Synchronous I/O calls",
    category: "performance",
    description: "Blocks blocking sync I/O (readFileSync, etc.) outside DevOps scripts.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-test-disabling-skipping",
    name: "Test disabling / skipping",
    category: "testing",
    description: "Blocks .skip/.only/.fixme/.skipIf/.todo, xit/xdescribe, fdescribe/fit, and this.skip() across test tiers.",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-coverage",
    name: "Coverage ratchet",
    category: "testing",
    description:
      "Blocks a drop in test coverage below the committed baseline (coverage-baseline.json); reads coverage/coverage-summary.json. Accept a new floor with --update.",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: RATCHET_MODES,
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "lint-tests-with-code",
    name: "Tests move with code",
    category: "testing",
    description:
      "Blocks staging a production source change (or new file) with no matching test change in the same commit — the deterministic TDD proxy.",
    languages: JSTS,
    config: null,
    ratchetable: true,
    modes: ["staged", "warn"],
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-empty-tests",
    name: "Empty tests",
    category: "testing",
    description:
      "Flags it()/test() with no callback or no assertion (expect/assert) — tests that pass vacuously.",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-test-determinism",
    name: "Test determinism",
    category: "testing",
    description:
      "Flags nondeterministic sources in tests — Date.now/new Date()/performance.now, Math.random, and real network (fetch/XMLHttpRequest).",
    languages: JSTS,
    config: null,
    ratchetable: false,
    modes: FILE_MODES,
    stages: ["pre-commit"],
  }),
  defineRule({
    slug: "lint-protected-paths",
    name: "Protected paths",
    category: "governance",
    description:
      "Blocks staging (git) or editing (Claude Code) any path matching the project's protected globs (project settings).",
    languages: [],
    config: null,
    ratchetable: false,
    modes: ["staged", "all", "files"],
    stages: ["pre-commit", "claude-tool"],
    settingsControls: ["protected-paths"],
  }),
  // Governance rules police the repo/workflow, not source files: language-agnostic
  // (languages: []) and enforced per environment via action bindings (e.g. halt on
  // github, warn on claude). The runnable ones delegate to a hooks/git/<slug>.mjs;
  // gov-require-pr is server-only (stage: "server") and carries no local runner.
  defineRule({
    slug: "gov-main-ci-green",
    name: "Block on red main CI",
    category: "governance",
    description:
      "Blocks commits/merges while the latest Tests run on main failed in a blocking job (gh). Bypass: ALLOW_COMMIT_ON_RED_MAIN=1.",
    languages: [],
    config: { branch: "main", blockingJobs: ["unit", "integration"] },
    ratchetable: false,
    modes: ["push", "warn"],
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "gov-no-push-to-main",
    name: "No direct commits on main",
    category: "governance",
    description:
      "Blocks committing directly on main/master; work must happen on a branch. Bypass: ALLOW_EDIT_ON_MAIN=1.",
    languages: [],
    config: { branches: ["main", "master"] },
    ratchetable: false,
    modes: ["push", "warn"],
    stages: ["pre-push"],
  }),
  defineRule({
    slug: "gov-require-pr",
    name: "Require pull request",
    category: "governance",
    description:
      "Policy: changes to main must land via pull request. Enforced server-side by GitHub branch protection (.github/rulesets/main.json); no local runner.",
    languages: [],
    config: { branch: "main", ruleset: ".github/rulesets/main.json" },
    ratchetable: false,
    modes: [],
    stages: ["server"],
    settingsControls: ["project-note"],
  }),
];
